# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MedicineInfodialogBox.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_medicineInfoDialog(object):
    def setupUi(self, medicineInfoDialog):
        medicineInfoDialog.setObjectName("medicineInfoDialog")
        medicineInfoDialog.setWindowModality(QtCore.Qt.WindowModal)
        medicineInfoDialog.resize(749, 479)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(medicineInfoDialog.sizePolicy().hasHeightForWidth())
        medicineInfoDialog.setSizePolicy(sizePolicy)
        medicineInfoDialog.setStyleSheet("")
        self.medicineInfolabel = QtWidgets.QLabel(medicineInfoDialog)
        self.medicineInfolabel.setGeometry(QtCore.QRect(270, 30, 201, 20))
        self.medicineInfolabel.setStyleSheet("font: 75 15pt \"Serif\";\n"
"text-decoration : underline;")
        self.medicineInfolabel.setObjectName("medicineInfolabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(medicineInfoDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 80, 141, 311))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.name_label.setStyleSheet("font: 75 15pt \"Serif\";")
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.quantity_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.quantity_label.setStyleSheet("font: 75 15pt \"Serif\";")
        self.quantity_label.setObjectName("quantity_label")
        self.verticalLayout.addWidget(self.quantity_label)
        self.price_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.price_label.setStyleSheet("font: 75 15pt \"Serif\";")
        self.price_label.setObjectName("price_label")
        self.verticalLayout.addWidget(self.price_label)
        self.batch_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.batch_label.setStyleSheet("font: 75 15pt \"Serif\";")
        self.batch_label.setObjectName("batch_label")
        self.verticalLayout.addWidget(self.batch_label)
        self.expiry_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.expiry_label.setStyleSheet("font: 75 15pt \"Serif\";")
        self.expiry_label.setObjectName("expiry_label")
        self.verticalLayout.addWidget(self.expiry_label)
        self.mfDate_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.mfDate_label.setStyleSheet("font: 75 15pt \"Serif\";")
        self.mfDate_label.setObjectName("mfDate_label")
        self.verticalLayout.addWidget(self.mfDate_label)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(medicineInfoDialog)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(210, 80, 481, 311))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nameInfo = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.nameInfo.setStyleSheet("font: 75 15pt \"Serif\";")
        self.nameInfo.setObjectName("nameInfo")
        self.verticalLayout_2.addWidget(self.nameInfo)
        self.quantityInfo = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.quantityInfo.setStyleSheet("font: 75 15pt \"Serif\";")
        self.quantityInfo.setObjectName("quantityInfo")
        self.verticalLayout_2.addWidget(self.quantityInfo)
        self.priceInfo = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.priceInfo.setStyleSheet("font: 75 15pt \"Serif\";")
        self.priceInfo.setObjectName("priceInfo")
        self.verticalLayout_2.addWidget(self.priceInfo)
        self.batchInfo = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.batchInfo.setStyleSheet("font: 75 15pt \"Serif\";")
        self.batchInfo.setObjectName("batchInfo")
        self.verticalLayout_2.addWidget(self.batchInfo)
        self.expDateInfo = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.expDateInfo.setStyleSheet("font: 75 15pt \"Serif\";")
        self.expDateInfo.setObjectName("expDateInfo")
        self.verticalLayout_2.addWidget(self.expDateInfo)
        self.mfdDateInfo = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.mfdDateInfo.setStyleSheet("font: 75 15pt \"Serif\";")
        self.mfdDateInfo.setObjectName("mfdDateInfo")
        self.verticalLayout_2.addWidget(self.mfdDateInfo)
        self.closeButton = QtWidgets.QPushButton(medicineInfoDialog)
        self.closeButton.setGeometry(QtCore.QRect(280, 430, 89, 25))
        self.closeButton.setObjectName("closeButton")

        self.retranslateUi(medicineInfoDialog)
        QtCore.QMetaObject.connectSlotsByName(medicineInfoDialog)

    def retranslateUi(self, medicineInfoDialog):
        _translate = QtCore.QCoreApplication.translate
        medicineInfoDialog.setWindowTitle(_translate("medicineInfoDialog", "Dialog"))
        self.medicineInfolabel.setText(_translate("medicineInfoDialog", "Medicine Info"))
        self.name_label.setText(_translate("medicineInfoDialog", "Name  "))
        self.quantity_label.setText(_translate("medicineInfoDialog", "Quantity"))
        self.price_label.setText(_translate("medicineInfoDialog", "Price"))
        self.batch_label.setText(_translate("medicineInfoDialog", "Batch No"))
        self.expiry_label.setText(_translate("medicineInfoDialog", "Expiry Date"))
        self.mfDate_label.setText(_translate("medicineInfoDialog", "MF Date"))
        self.nameInfo.setText(_translate("medicineInfoDialog", "Mediine Name"))
        self.quantityInfo.setText(_translate("medicineInfoDialog", "Quantity Name "))
        self.priceInfo.setText(_translate("medicineInfoDialog", "Price  info"))
        self.batchInfo.setText(_translate("medicineInfoDialog", "Batch info"))
        self.expDateInfo.setText(_translate("medicineInfoDialog", "Exp Date INFO"))
        self.mfdDateInfo.setText(_translate("medicineInfoDialog", "mfDateInfo"))
        self.closeButton.setText(_translate("medicineInfoDialog", "CLOSE "))

